config/routes.rb
Rails.application.routes.draw do
  root "home#index"
  resources :drafts
  resources :news
  resources :commissioners
  resources :drafts
  resources :headlines
  resources :leagues do
    resources :dues
    resources :managers
  end

  get '/leagues/:id/finances' => 'leagues#get_finances', as: 'league_finances'
  get '/leagues/:id/manage_finances' => 'leagues#manage_finances', as: "manage_finances"
  get '/leagues/:id/back' => 'leagues#back', as: 'league_back'
  get '/managers/text/:id' => 'managers#write_text', as: 'write_text'
  post '/managers/text/:id' => 'managers#send_text', as: 'send_text'
  post 'twilio/text/:id' => 'twilio#send_text_message', as: 'twilio_text'
  get 'managers/email/:id' => 'managers#write_email', as: 'email'
  post 'managers/email/:id' => 'managers#send_email', as: 'send_email'
  get 'leagues/email/:id' => 'leagues#write_email', as: 'league_email'
  post 'leages/email/:id' => 'leagues#send_email', as: 'league_send_email'
  get 'managers/prompt/:id' => 'managers#prompt', as: 'prompt'
  get 'homescreen' => 'home#back'
  get '/signup' => 'commissioners#new'
  post '/signup' => 'commissioners#create'
  get '/login' => 'sessions#new'
  post '/login' => 'sessions#create'
  get '/logout' => 'sessions#destroy'
  get '/dues/pay/:id' => 'dues#pay', as: 'pay'
  get '/leagues/:id/dues_text' => 'dues#write_text', as: 'dues_text'
  post '/leagues/:id/dues_text' => 'dues#text_non_payers', as: 'send_dues_text'

end

app/models/league.rb
class League < ActiveRecord::Base
  belongs_to :commissioner
  has_many :managers
  has_many :dues

  def amount_paid
    if self.commissioner.due
      paid = self.dues.select {|due| due.paid }.count
      total = (self.commissioner.due.amount * paid)
    else
      total = 0
    end
    total
  end
end

app/controllers/leagues_controller.rb
class LeaguesController < ApplicationController
  def new
    @league = League.new
    @headlines = Headlines.get_headlines
  end

  def write_email
    @league = current_user.leagues.first
    @managers = current_user.leagues.first.managers
    @league = current_user.leagues.first
    @headlines = Headlines.get_headlines
    respond_to do |format|
      format.js
    end
  end

  def manage_finances
    @dues = current_user.leagues.first.dues
    @managers = current_user.leagues.first.managers
    @league = current_user.leagues.first
    @headlines = Headlines.get_headlines
    respond_to do |format|
      format.js
    end
  end

  def back
    @league = current_user.leagues.first
    @commissioner = current_user
    @managers = @league.managers
    respond_to do |format|
      format.js
    end
  end

  def get_finances
    @dues = current_user.leagues.first.dues
    @managers = current_user.leagues.first.managers
    @league = current_user.leagues.first
    @headlines = Headlines.get_headlines
    respond_to do |format|
      format.js
    end
  end

  def send_email
    @league = League.find_by(id: params[:id])
    @managers = @league.managers
    @subject = params[:subject]
    @content = params[:content]
    @manager_emails = @managers.map {|manager| manager.email}
    @commissioner = current_user
    UserMailer.league(@manager_emails, @commissioner, @subject, @content).deliver_now
    respond_to do |format|
      format.js
    end
  end

  def create
    @league = League.new(league_params)
    if league_params["name"].blank?
      flash[:danger] = "You need to give a name for your league"
      redirect_to :back
    else
      @league.commissioner_id = current_user.id
      @league.save
      redirect_to league_path(@league)
    end
    @headlines = Headlines.get_headlines
  end

  def show
    @league = current_user.leagues.first
    @headlines = Headlines.get_headlines
  end

private

  def league_params
    params.require(:league).permit(:name)
  end

end

app/helpers/leagues_helper.rb
module LeaguesHelper
end

app/views/leagues/_dashboard_jumbotron.html.erb
  <!-- HOME -->
  <section class="module module-header bg-dark bg-dark-50" data-background="http://images.123hdwallpapers.com/20150517/sports-wallpaper-american-football-1024x768.jpg">

    <div class="container">

      <!-- MODULE TITLE -->
      <div class="row">

        <div class="col-sm-6 col-sm-offset-3">

          <h1 class="module-title font-alt align-center"><%= current_user.name.upcase %>'s DASHBOARD </h1>

          <div class="module-subtitle font-inc align-center">
          <% if current_user.leagues.first %>
        <marquee>Top Headlines from Bleacher Report:
            <% @headlines.each do |title, link| %>
            <%= link_to title, link, :target => '_blank', :id => 'headlines' %> &emsp;
            <% end %>
            <% end %></marquee>
          </div>

        </div>

      </div>
      <!-- /MODULE TITLE -->

    </div>

  </section >

app/views/leagues/_finances.html.erb
  <div class="work-details">
    <h2 class="work-details-title font-alt">Who's Paid</h2>
    <% @managers.each do |manager| %>
        <% if !manager.due.paid %>
          <h4 class="font-inc"><strong><%= manager.name %></strong> owes $<%= manager.due.amount %></span>
        <% end %>
      <% end %>
        <% if !@league.commissioner.due.paid %>
        <h4 class="font-inc"><strong>You</strong> owe $<%= @league.commissioner.due.amount %></span>
        <% end %><br>
  </div>

app/views/leagues/_manage_finances.html.erb
<div class="work-details">
  <h2 class="work-details-title font-alt">Manage Payments</h2>
  <% @managers.each do |manager| %>
      <% if !manager.due.paid %>
        <h4 class="font-inc"><strong><%= manager.name %></strong> owes $<%= manager.due.amount %></span>
        <%= link_to 'Unpaid', pay_path(manager.due), class: "btn btn-border-d btn-circle", remote: true %>
        <% else %>
        <h4 class="font-inc"><strong><%= manager.name %></strong> has paid</span>
        <%= link_to 'Paid', pay_path(manager.due), class: "btn btn-d btn-circle", remote: true %>
      <% end %>
    <% end %>
      <% if !@league.commissioner.due.paid %>
      <h4 class="font-inc"><strong>You</strong> owe $<%= @league.commissioner.due.amount %></span>
      <%= link_to 'Unpaid', pay_path(@league.commissioner.due), class: "btn btn-border-d btn-circle", remote: true  %>
      <% else %>
      <h4 class="font-inc"><strong>You</strong> have paid</span>
      <%= link_to 'Paid', pay_path(@league.commissioner.due), class: "btn btn-d btn-circle", remote: true  %>
      <% end %><br>
</div>

app/views/leagues/_show.html.erb
<section class="module-small p-t-20 p-b-60">

  <div class="container">

    <!-- PORTFOLIO FILTER -->
    <div class="row">
      <div class="col-sm-12">

        <ul id="filters" class="filter font-inc hidden-xs">
          <li><a href="#" data-filter=".manager" class="wow fadeInUp" data-wow-delay="0.2s">Managers</a></li>
          <li><a href="#" data-filter=".finance" class="wow fadeInUp" data-wow-delay="0.4s">Finances</a></li>
          <li><a href="#" data-filter=".draft" class="wow fadeInUp" data-wow-delay="0.6s">Draft</a></li>
          <li><a href="#" data-filter=".news" class="wow fadeInUp" data-wow-delay="0.8s">NFL News</a></li>
          <li><a href="#" data-filter="*" class="wow fadeInUp" data-wow-delay="0.8s">All</a></li>
        </ul>

      </div>
    </div>
    <!-- /PORTFOLIO FILTER -->

    <!-- PORTFOLIO LIST -->
    <ul id="works-grid" class="works-grid works-grid-gut works-grid-3 works-hover-w">

      <!-- PORTFOLIO ITEM -->
      <% if !@league.commissioner.due %>
      <li class="work-item finance">
         <%= link_to new_league_due_path(@league) do %>
          <div class="work-image">
            <img id = "tile" src="https://pbs.twimg.com/media/CBOuWhBUkAENRiA.jpg" alt="">
          </div>
          <div class="work-caption">
            <h3 class="work-title font-alt">Set League Dues</h3>
            <div class="work-descr font-inc">
              Set the Dues Amount for League Managers
            </div>
          </div>
        <% end %>
      </li>
      <% end %>
      <!-- /PORTFOLIO ITEM -->

      <!-- PORTFOLIO ITEM -->
      <li class="work-item manager">
        <%= link_to league_managers_path(@league), remote: true do %>
          <div class="work-image">
            <img id="tile" src="https://pbs.twimg.com/media/CBZIQHHWgAAIBk0.jpg:large" alt="">
          </div>
          <div class="work-caption">
            <h3 class="work-title font-alt">
              <% if @league.managers.count == 0 %>
              Add Managers
              </h3>
            <div class="work-descr font-inc">
              Add managers to <%= @league.name %>
            </div>
            <% else %>
            View Managers
            </h3>
          <div class="work-descr font-inc">
            Edit, Delete, and communicate with managers in <%= @league.name %>
          </div>
          <% end %>
          </div>
        <% end %>
      </li>
      <!-- /PORTFOLIO ITEM -->

      <!-- PORTFOLIO ITEM -->
      <li class="work-item finance">
        <%= link_to league_dues_path(@league) do %>
          <div class="work-image">
            <img id = "tile" src="https://pbs.twimg.com/media/CBZHHaIVAAANnlV.jpg" alt="">
          </div>
          <div class="work-caption">
            <h3 class="work-title font-alt">League Finances</h3>
            <div class="work-descr font-inc">
              See who has paid league dues
            </div>
          </div>
        <% end %>
      </li>
      <!-- /PORTFOLIO ITEM -->

      <!-- PORTFOLIO ITEM -->
      <li class="work-item manager">
        <%= link_to league_email_path(@league), remote: true do %>
          <div class="work-image">
            <img id = "tile" src="https://pbs.twimg.com/media/CBJZqrfWgAAzPOp.jpg:large" alt="">
          </div>
          <div class="work-caption">
            <h3 class="work-title font-alt">Email Entire League</h3>
            <div class="work-descr font-inc">
              Draft and send league emails
            </div>
          </div>
        <% end %>
      </li>
      <!-- /PORTFOLIO ITEM -->

      <!-- PORTFOLIO ITEM -->
      <li class="work-item news">
        <%= link_to headlines_path do %>
          <div class="work-image">
            <img id = "tile" src="https://pbs.twimg.com/media/CBI7ztQU0AARigs.jpg" alt="">
          </div>
          <div class="work-caption">
            <h3 class="work-title font-alt">NFL News</h3>
            <div class="work-descr font-inc">
              Top Stories and Injury Report
            </div>
          </div>
        <% end %>
      </li>
      <!-- /PORTFOLIO ITEM -->

      <!-- PORTFOLIO ITEM -->
      <li class="work-item draft">
        <%= link_to drafts_path do %>
          <div class="work-image">
            <img id = "tile"  src="https://pbs.twimg.com/media/CA_LuoGUYAEq-sm.jpg" alt="">
          </div>
          <div class="work-caption">
            <h3 class="work-title font-alt">Schedule Draft</h3>
            <div class="work-descr font-inc">
              Calendar
            </div>
          </div>
        </a>
        <% end %>
      </li>
      <!-- /PORTFOLIO ITEM -->

      <!-- PORTFOLIO ITEM -->
      <li class="work-item finance">
        <a href="portfolio-single-1.html">
          <div class="work-image">
            <img id = "tile" src="https://pbs.twimg.com/media/CBZFRwnUYAAX8F2.jpg" alt="">
          </div>
          <div class="work-caption">
            <h3 class="work-title font-alt">Text Non-Payers</h3>
            <div class="work-descr font-inc">
              Remind your non-paying members
            </div>
          </div>
        </a>
      </li>
      <!-- /PORTFOLIO ITEM -->

      <!-- PORTFOLIO ITEM -->
      <li class="work-item manager">
        <a href="portfolio-single-1.html">
          <div class="work-image">
            <img id = "tile" src="https://pbs.twimg.com/media/CBZEQ4gWgAEdYR1.jpg" alt="">
          </div>
          <div class="work-caption">
            <h3 class="work-title font-alt">Set lineup reminder</h3>
            <div class="work-descr font-inc">
              Schedule reminder text for your managers to set-lineups
            </div>
          </div>
        </a>
      </li>
      <!-- /PORTFOLIO ITEM -->
    </ul>
    <!-- /PORTFOLIO LIST -->

  </div>

</section>
<!-- /PORTFOLIO -->

<!-- FOOTER -->

<%= render "layouts/footer" %>
<!-- /FOOTER -->

app/views/leagues/_write_email.html.erb
<div class="container">

  <!-- PORTFOLIO FILTER -->
  <div class="row">
    <div class="col-sm-12">

      <ul id="filters" class="filter font-inc hidden-xs">
        <li><%= link_to 'Back', league_back_path(@league), remote: true %></li>
      </ul>

    </div>
  </div>
<div class="container">
  <div class="row">
    <div class="col-sm-8 col-sm-offset-2" id="main-panel">
        <h2 class="work-details-title font-alt">Email League</h2>
        <%= form_tag league_send_email_path(@league), {remote: true} do %>
         <div class="form-group">
            <%= text_field_tag :subject, nil, class: "form-control input-lg", placeholder: "Subject" %>
         </div>
         <div class="form-group">
           <%= text_area_tag :content, nil, class: "form-control input-lg", placeholder: "Message", rows: 10  %>
         </div>
           <%= submit_tag "Send Email", class: "btn btn-d btn-circle btn-lg", remote: true %>
         <% end %>
         </div>
      <!-- POST WITH IMAGE -->

    </div>
  </div>
</div>
</div>

app/views/leagues/back.js.erb
$(".module-small").html("")
$(".module-small").append("<%= j render partial: 'leagues/show' %>").hide().fadeIn()

app/views/leagues/get_finances.js.erb
$("#side-panel").html("")
$("#side-panel").append("<%= j render :partial => 'leagues/finances' %>").hide().fadeIn()

app/views/leagues/manage_finances.js.erb
$("#side-panel").html("")
$("#side-panel").append("<%= j render :partial => 'leagues/manage_finances' %>").hide().fadeIn()

app/views/leagues/new.html.erb
<!-- WRAPPER -->
<div class="wrapper">

  <!-- HOME -->
  <%= render "leagues/dashboard_jumbotron" %>
  <!-- /HOME -->
		<!-- PORTFOLIO -->
		<section class="module-small p-t-20 p-b-60" id="League_Create_Form">

			<div class="container">

        <!-- NEW LEAGUE FORM -->
        <div class="row">
        <h4 class="font-alt m-t-0 m-b-0">Create New League</h4>
       <hr class="divider-w m-t-10 m-b-20">

<!--        <div class="form-group">
          <input class="form-control input-lg" type="text" placeholder="EMAIL">
        </div>
        <div class="form-group">
          <input class="form-control input-lg" type="text" placeholder="PASSWORD">
        </div> -->
        <%= form_for @league do |f| %>
            <%= f.label :name %>
            <%= f.text_field :name %>
            <%= f.submit 'Create', class: "btn btn-g btn-circle btn-lg", id: "League_Create" %>
        <% end %>
        <br>

      </div>
    </div>
  </section>
<div>
        <!-- /NEW LEAGUE FORM -->



        		<!-- FOOTER -->


        		<!-- /FOOTER -->

app/views/leagues/send_email.js.erb
$("#main-panel").html("")
$("#main-panel").append("<div class=well well-sm'><strong>Email Sent to League</div>").hide().fadeIn()

app/views/leagues/show.html.erb
<!-- WRAPPER -->
<div class="wrapper">

  <!-- HOME -->
  <%= render partial: "leagues/dashboard_jumbotron", locals: {league: @league} %>

  <!-- /HOME -->
		<!-- PORTFOLIO -->
  <%= render partial: 'leagues/show', locals: {league: @league} %>

app/views/leagues/write_email.html.erb
<!-- WRAPPER -->
<div class="wrapper">

  <!-- HOME -->
  <%= render partial: "leagues/dashboard_jumbotron", locals: {league: @league} %>
  <!-- /HOME -->
		<!-- PORTFOLIO -->
    <div class="container">
      <div class="row">
        <div class="col-sm-8 col-sm-offset-2" id="main-panel">
            <h2 class="work-details-title font-alt">Email League</h2>
            <%= form_tag league_send_email_path(@league), {remote: true} do %>
             <div class="form-group">
                <%= text_field_tag :subject, nil, class: "form-control input-lg", placeholder: "Subject" %>
             </div>
             <div class="form-group">
               <%= text_area_tag :content, nil, class: "form-control input-lg", placeholder: "Message", rows: 10  %>
             </div>
               <%= submit_tag "Send Email", class: "btn btn-d btn-circle btn-lg", remote: true %>
             <% end %>
             </div>
          <!-- POST WITH IMAGE -->

        </div>
      </div>
    </div>
</div>
        <!-- /NEW LEAGUE FORM -->



        		<!-- FOOTER -->


        		<!-- /FOOTER -->

app/views/leagues/write_email.js.erb
$(".module-small").html("")
$(".module-small").append("<%= j render partial: 'leagues/write_email' %>").hide().fadeIn()