config/routes.rb
Rails.application.routes.draw do
  root "home#index"
  resources :drafts
  resources :news
  resources :commissioners
  resources :drafts
  resources :headlines
  resources :leagues do
    resources :dues
    resources :managers
  end

  get '/leagues/:id/finances' => 'leagues#get_finances', as: 'league_finances'
  get '/leagues/:id/manage_finances' => 'leagues#manage_finances', as: "manage_finances"
  get '/leagues/:id/back' => 'leagues#back', as: 'league_back'
  get '/managers/text/:id' => 'managers#write_text', as: 'write_text'
  post '/managers/text/:id' => 'managers#send_text', as: 'send_text'
  post 'twilio/text/:id' => 'twilio#send_text_message', as: 'twilio_text'
  get 'managers/email/:id' => 'managers#write_email', as: 'email'
  post 'managers/email/:id' => 'managers#send_email', as: 'send_email'
  get 'leagues/email/:id' => 'leagues#write_email', as: 'league_email'
  post 'leages/email/:id' => 'leagues#send_email', as: 'league_send_email'
  get 'managers/prompt/:id' => 'managers#prompt', as: 'prompt'
  get 'homescreen' => 'home#back'
  get '/signup' => 'commissioners#new'
  post '/signup' => 'commissioners#create'
  get '/login' => 'sessions#new'
  post '/login' => 'sessions#create'
  get '/logout' => 'sessions#destroy'
  get '/dues/pay/:id' => 'dues#pay', as: 'pay'
  get '/leagues/:id/dues_text' => 'dues#write_text', as: 'dues_text'
  post '/leagues/:id/dues_text' => 'dues#text_non_payers', as: 'send_dues_text'

end

app/models/manager.rb
class Manager < ActiveRecord::Base
  has_one :due
  belongs_to :league
  has_one :due

  validates_format_of :phone_number, :with =>  /\d[0-9]\)*\z/ , :message => "Please enter a valid phone number"

end

app/controllers/managers_controller.rb
class ManagersController < ApplicationController
  def index
    @league = current_user.leagues.first
    @managers = current_user.leagues.first.managers
    @headlines = Headlines.get_headlines
    respond_to do |format|
      format.js
    end
  end

  def write_text
    @league = current_user.leagues.first
    @manager = Manager.find_by(id: params[:id])
    respond_to do |format|
      format.js
    end
  end

  def send_text
    @manager = Manager.find_by(id: params[:id])
    number = @manager.phone_number
    @message = params[:message]
    twilio_token = ENV["TWILIO_TOKEN"]
    twilio_sid = ENV["TWILIO_SID"]
    twilio_phone_number = ENV["TWILIO_PHONE_NUMBER"]

    @twilio_client = Twilio::REST::Client.new twilio_sid, twilio_token
    @twilio_client.messages.create(
      :from => "+1#{twilio_phone_number}",
      :to => number,
      :body => "#{@message}"
    )
    respond_to do |format|
      format.js
    end
  end

  def new
    @managers = current_user.leagues.first.managers
    @league = current_user.leagues.first
    @manager = Manager.new
    @headlines = Headlines.get_headlines
    respond_to do |format|
      format.js
    end
  end

  def edit
    @league = current_user.leagues.first
    @manager = Manager.find_by(id: params[:id])
    respond_to do |format|
      format.js
    end
  end

  def update
    @manager = Manager.find_by(id: params[:id])
    @manager = @manager.update(manager_params)
    @managers = current_user.leagues.first.managers
    @league = current_user.leagues.first
    respond_to do |format|
      format.js
    end
  end

  def prompt
    @manager = Manager.find_by(id: params[:id])
    @league = @manager.league
    respond_to do |format|
      format.js
    end
  end

  def write_email
    @manager = Manager.find_by(id: params[:id])
    @league = @manager.league
    respond_to do |format|
      format.js
    end
  end

  def send_email
    @subject = params[:subject]
    @content = params[:content]
    @manager = Manager.find_by(id: params[:id])
    @commissioner = current_user
    UserMailer.manager(@manager, @commissioner, @subject, @content).deliver_now
    respond_to do |format|
      format.js
    end
  end

  def destroy
    @manager = Manager.find_by(id: params[:id])
    @league = @manager.league
    @manager.destroy
    @league = current_user.leagues.first
    @managers = current_user.leagues.first.managers
    respond_to do |format|
      format.js
    end
  end

  def create
    @managers = current_user.leagues.first.managers
    @manager = Manager.new(manager_params)
    if manager_params["name"].blank? || manager_params["email"].blank? || manager_params["phone_number"].blank?
    flash[:danger] = "You were missing attributes for manager"
    redirect_to :back
    else
    @league = League.find_by(id: params[:league_id])
    end
    @manager.league_id = params[:league_id]
    @manager.save
    @commissioner = current_user
    UserMailer.welcome(@manager, @commissioner).deliver_now
    if current_user.due
    @manager.due = Due.create(amount: current_user.due.amount, manager_id: @manager.id, league_id: @league.id)
    end
    respond_to do |format|
      format.js
    end
  end

  def show
    @league = current_user.leagues.first
    @manager = Manager.find_by(id: params[:id])
    @headlines = Headlines.get_headlines
  end

private
  def manager_params
    params.require(:manager).permit(:name, :email, :phone_number)
  end
end

app/helpers/managers_helper.rb
module ManagersHelper
end

app/views/managers/_edit.html.erb
<div class="work-details">
  <h2 class="work-details-title font-alt">Edit <%= @manager.name %></h2>
  <%= form_for [@league, @manager], remote: true do |f| %>
   <div class="form-group">
      <%= f.text_field :name, class: "form-control input-lg", placeholder: "Name" %>
   </div>
   <div class="form-group">
     <%= f.text_field :email, class: "form-control input-lg", placeholder: "Email" %>
   </div>
   <div class="form-group">
     <%= f.text_field :phone_number, class: "form-control input-lg", placeholder: "Phone Number" %>
   </div>
     <%= f.submit "Edit Manager", class: "btn btn-d btn-circle btn-lg", remote: true %>
   <% end %>
   </div>

app/views/managers/_email.html.erb
<div class="work-details">
  <h2 class="work-details-title font-alt">Email <%= @manager.name %></h2>
  <%= form_tag send_email_path, {remote: true} do %>
   <div class="form-group">
      <%= text_field_tag :subject, nil, class: "form-control input-lg", placeholder: "Subject" %>
   </div>
   <div class="form-group">
     <%= text_area_tag :content, nil, class: "form-control input-lg", placeholder: "Message", rows: 10  %>
   </div>
     <%= submit_tag "Send Email", class: "btn btn-d btn-circle btn-lg", remote: true %>
   <% end %>
   </div>

app/views/managers/_new.html.erb
<div class="work-details">
  <h3 class="work-details-title font-alt">Add Manager</h3>
  <%= form_for [@league, @manager], remote: true do |f| %>
   <div class="form-group">
      <%= f.text_field :name, class: "form-control input-lg", placeholder: "Name" %>
   </div>
   <div class="form-group">
     <%= f.text_field :email, class: "form-control input-lg", placeholder: "Email" %>
   </div>
   <div class="form-group">
     <%= f.text_field :phone_number, class: "form-control input-lg", placeholder: "Phone Number" %>
   </div>
     <%= f.submit "Create Manager", class: "btn btn-d btn-circle btn-lg" %>
   <% end %>
   </div>
</div>

app/views/managers/_prompt.html.erb
<div class="work-details">
  <h2 class="work-details-title font-alt">Are you sure you want to delete <%= @manager.name %>?</h2><br>
  <%= link_to 'DELETE', league_manager_path(@league, @manager), method: :delete, class: "btn btn-d btn-circle btn-lg", remote: true %>
   </div>

app/views/managers/_text.html.erb
<div class="work-details">
  <h2 class="work-details-title font-alt">Text <%= @manager.name %></h2>
  <%= form_tag send_text_path(@manager), {remote: true} do %>
   <div class="form-group">
     <%= text_area_tag :message, nil, class: "form-control input-lg", placeholder: "Message", rows: 10  %>
   </div>
     <%= submit_tag "Send Text", class: "btn btn-d btn-circle btn-lg", remote: true %>
   <% end %>
   </div>

app/views/managers/create.js.erb
$("#main-panel").html("")
$("#main-panel").append("<%= j render :partial => 'managers/managers' %>").hide().fadeIn()
$("#side-panel").append("<div class=well well-sm'><strong>Manager Added. Notification Email Sent")

$("input#manager_name").val("")
$("input#manager_email").val("")
$("input#manager_phone_number").val("")

app/views/managers/index.js.erb
$(".module-small").html("")
$(".module-small").append("<%= j render partial: 'managers/index' %>").hide().fadeIn()

app/views/managers/prompt.js.erb
$("#side-panel").html("")
$("#side-panel").append("<%= j render :partial => 'managers/prompt' %>").hide().fadeIn()

app/views/managers/send_email.js.erb
$("#side-panel").html("")
$("#side-panel").append("<div class=well well-sm'><strong>Email Sent</div>")

app/views/managers/send_text.js.erb
$("#side-panel").html("")
$("#side-panel").append("<div class=well well-sm'><strong>Text Sent</div>")

app/views/managers/show.html.erb
<div class="wrapper">

  <!-- HOME -->
  <%= render partial: "leagues/dashboard_jumbotron", locals: {league: @league} %>
   <!-- /HOME -->
   <!-- PORTFOLIO DESCRIPTION -->
   <%= render "layouts/messages" %>
   <section class="module-small">

     <div class="container">

       <div class="row">

         <div class="col-sm-6">

           <div class="work-details">
             <h3 class="work-details-title font-alt"><%= @manager.name %></h3>
           </div>

         </div>

         <div class="col-sm-6">

  
       </div>

     </div>

   </section>

app/views/managers/update.js.erb
$("#main-panel").html("")
$("#main-panel").append("<%= j render :partial => 'managers/managers' %>").hide().fadeIn()
$("#side-panel").html("")
$("#side-panel").append("<div class=well well-sm'><strong>Edit Successful</div>")

app/views/managers/write_email.js.erb
$("#side-panel").html("")
$("#side-panel").append("<%= j render :partial => 'managers/email' %>").hide().fadeIn()

app/views/managers/write_text.js.erb
$("#side-panel").html("")
$("#side-panel").append("<%= j render :partial => 'managers/text' %>").hide().fadeIn()