config/routes.rb
Rails.application.routes.draw do
  root "home#index"
  resources :drafts
  resources :news
  resources :commissioners
  resources :drafts
  resources :headlines
  resources :leagues do
    resources :dues
    resources :managers
  end

  get '/leagues/:id/finances' => 'leagues#get_finances', as: 'league_finances'
  get '/leagues/:id/manage_finances' => 'leagues#manage_finances', as: "manage_finances"
  get '/leagues/:id/back' => 'leagues#back', as: 'league_back'
  get '/managers/text/:id' => 'managers#write_text', as: 'write_text'
  post '/managers/text/:id' => 'managers#send_text', as: 'send_text'
  post 'twilio/text/:id' => 'twilio#send_text_message', as: 'twilio_text'
  get 'managers/email/:id' => 'managers#write_email', as: 'email'
  post 'managers/email/:id' => 'managers#send_email', as: 'send_email'
  get 'leagues/email/:id' => 'leagues#write_email', as: 'league_email'
  post 'leages/email/:id' => 'leagues#send_email', as: 'league_send_email'
  get 'managers/prompt/:id' => 'managers#prompt', as: 'prompt'
  get 'homescreen' => 'home#back'
  get '/signup' => 'commissioners#new'
  post '/signup' => 'commissioners#create'
  get '/login' => 'sessions#new'
  post '/login' => 'sessions#create'
  get '/logout' => 'sessions#destroy'
  get '/dues/pay/:id' => 'dues#pay', as: 'pay'
  get '/leagues/:id/dues_text' => 'dues#write_text', as: 'dues_text'
  post '/leagues/:id/dues_text' => 'dues#text_non_payers', as: 'send_dues_text'

end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end

  def back
    respond_to do |format|
      format.js
    end
  end
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/home/_landing_jumbotron.html.erb
<section class="module-hero module-parallax module-fade module-full-height bg-dark-30" data-background="http://images.123hdwallpapers.com/20150517/sports-wallpaper-american-football-1024x768.jpg">

  <div class="hs-caption container">
    <div class="caption-content">
      <div class="hs-title-size-4 font-alt m-b-30">
            Welcome to Commissioner Dashboard
              <div class="hs-title-size-1 font-inc">
                      EST 2016
              </div>
      </div>
  <% if signed_in?  %>
    <a class="btn btn-g btn-circle btn-lg" id="Dashboard" href="leagues/<%=current_user.id%>"></i>Dashboard</a>
  <% else  %>
    <%= link_to 'Sign-Up', signup_path, class: "btn btn-g btn-circle btn-lg", remote: true %>
    <%= link_to 'Log-In', login_path, class: "btn btn-g btn-circle btn-lg", remote: true %>
  <% end %>
    </div>
  </div>
</section >

app/views/home/_landing_text.html.erb
  <div class="caption-content">
    <div class="hs-title-size-4 font-alt m-b-30">
          Welcome to Commissioner Dashboard
            <div class="hs-title-size-1 font-inc">
                    EST 2016
            </div>
          <%= link_to 'Sign-Up', signup_path, class: "btn btn-g btn-circle btn-lg", remote: true %>
          <%= link_to 'Log-In', login_path, class: "btn btn-g btn-circle btn-lg", remote: true %>
    </div>
  </div>

app/views/home/back.js.erb
$(".caption-content").remove()

$(".hs-caption").append("<%= j render(:partial => 'home/landing_text') %>").hide().fadeIn()

app/views/home/index.html.erb
<%= render "home/landing_jumbotron" %>