config/routes.rb
Rails.application.routes.draw do
  root "home#index"
  resources :drafts
  resources :news
  resources :commissioners
  resources :drafts
  resources :headlines
  resources :leagues do
    resources :dues
    resources :managers
  end

  get '/leagues/:id/finances' => 'leagues#get_finances', as: 'league_finances'
  get '/leagues/:id/manage_finances' => 'leagues#manage_finances', as: "manage_finances"
  get '/leagues/:id/back' => 'leagues#back', as: 'league_back'
  get '/managers/text/:id' => 'managers#write_text', as: 'write_text'
  post '/managers/text/:id' => 'managers#send_text', as: 'send_text'
  post 'twilio/text/:id' => 'twilio#send_text_message', as: 'twilio_text'
  get 'managers/email/:id' => 'managers#write_email', as: 'email'
  post 'managers/email/:id' => 'managers#send_email', as: 'send_email'
  get 'leagues/email/:id' => 'leagues#write_email', as: 'league_email'
  post 'leages/email/:id' => 'leagues#send_email', as: 'league_send_email'
  get 'managers/prompt/:id' => 'managers#prompt', as: 'prompt'
  get 'homescreen' => 'home#back'
  get '/signup' => 'commissioners#new'
  post '/signup' => 'commissioners#create'
  get '/login' => 'sessions#new'
  post '/login' => 'sessions#create'
  get '/logout' => 'sessions#destroy'
  get '/dues/pay/:id' => 'dues#pay', as: 'pay'
  get '/leagues/:id/dues_text' => 'dues#write_text', as: 'dues_text'
  post '/leagues/:id/dues_text' => 'dues#text_non_payers', as: 'send_dues_text'

end

app/models/due.rb
class Due < ActiveRecord::Base
  belongs_to :league
  belongs_to :commissioner
  belongs_to :manager
end

app/controllers/dues_controller.rb
class DuesController < ApplicationController

  def index
    @dues = current_user.leagues.first.dues
    @managers = current_user.leagues.first.managers
    @league = current_user.leagues.first
    @headlines = Headlines.get_headlines
  end

  def write_text
    @league = current_user.leagues.first
  respond_to do |format|
    format.js
  end
  end

  def text_non_payers
    @managers = current_user.leagues.first.managers.select {|manager| !manager.due.paid}
    @message = params[:message]
    twilio_token = ENV["TWILIO_TOKEN"]
    twilio_sid = ENV["TWILIO_SID"]
    twilio_phone_number = ENV["TWILIO_PHONE_NUMBER"]
    @twilio_client = Twilio::REST::Client.new twilio_sid, twilio_token
    @managers.each do |manager|
    @twilio_client.messages.create(
      :from => "+1#{twilio_phone_number}",
      :to => manager.phone_number,
      :body => "#{@message}"
    )
    end
    respond_to do |format|
      format.js
    end
  end

  def new
    @due = Due.new
    @league = current_user.leagues.first
    @headlines = Headlines.get_headlines
  end

  def create
    commish_due = Due.new(due_params)
    commish_due.commissioner_id = current_user.id
    commish_due.league_id = params[:league_id]
    commish_due.save

    @league = League.find(params[:league_id])
    @league.managers.each do |manager|
      due = Due.new(due_params)
      due.manager_id = manager.id
      due.league_id = params[:league_id]
      due.save
    end
    redirect_to league_dues_path(@league)
  end

  def edit

  end

  def update
    @due = Due.find(params[:id])
  end

  def show
    @due = Due.find(params[:id])
    @headlines = Headlines.get_headlines
  end

  def destroy
  end

  def pay
    @league = current_user.leagues.first
    @managers = current_user.leagues.first.managers
    @due = Due.find_by(id: params[:id])
    @due.paid = true
    @due.save
    respond_to do |format|
      format.js
    end
  end

  private

  def due_params
    params.require(:due).permit(:amount)
  end

end

app/helpers/due_helper.rb
module DueHelper
end

app/views/dues/_index.html.erb
<section class="module-small p-t-20 p-b-60">

<div class="container">

  <!-- PORTFOLIO FILTER -->
  <div class="row">
    <div class="col-sm-12">

      <ul class="filter font-inc hidden-xs">
        <li><%= link_to 'Manage Payments', manage_finances_path(@league), remote: true %></li>
        <li><%= link_to 'Text Non-Payers', dues_text_path(@league), remote: true %></li>
      </ul>

    </div>
  </div>
<div class="container">

  <div class="row">

    <div class="col-sm-6" id="main-panel">


   <%= render partial: "dues/pot" %>
      </div>

    </div>

    <div class="col-sm-6" id="side-panel">

  </div>

</div>

</section>

app/views/dues/_pot.html.erb
<div class="work-details">
<h2 class="work-details-title font-alt">League Finances</h2>
<ul id="finances">
  <% if @league.commissioner.due.amount %>
  <h4><li class="font-inc">League Pot: $<%= (@league.managers.count + 1) * (@league.commissioner.due.amount) %></h4>
  <h4><li class="font-inc">Total Collected: $<%= @league.amount_paid %></h4>
  <h4><li class="font-inc">Buy In: $<%= @league.commissioner.due.amount %></h4>
  <% else %>
  <h4><li class="font-inc">No Dues Set</h4>
  <% end %>
</ul>

app/views/dues/_text.html.erb
<div class="work-details">
  <h2 class="work-details-title font-alt">Text Non-Payers</h2>
  <%= form_tag send_dues_text_path(@league), {remote: true} do %>
   <div class="form-group">
     <%= text_area_tag :message, nil, class: "form-control input-lg", placeholder: "Message", rows: 10  %>
   </div>
     <%= submit_tag "Send Text", class: "btn btn-d btn-circle btn-lg", remote: true %>
   <% end %>
   </div>

app/views/dues/index.html.erb
<!-- WRAPPER -->
<div class="wrapper">

  <!-- HOME -->
  <%= render partial: "leagues/dashboard_jumbotron", locals: {league: @league} %>

  <!-- /HOME -->
		<!-- PORTFOLIO -->
  <%= render partial: 'dues/index', locals: {league: @league} %>

app/views/dues/new.html.erb
<!-- WRAPPER -->
<div class="wrapper">

  <!-- HOME -->
  <%= render partial: "leagues/dashboard_jumbotron", locals: {league: @league}%>
  <!-- /HOME -->
		<!-- PORTFOLIO -->
		<section class="module-small p-t-20 p-b-60" id="League_Create_Form">

			<div class="container">

        <!-- NEW LEAGUE FORM -->
        <div class="row">
        <h4 class="font-alt m-t-0 m-b-0">League Buy-In</h4>
       <hr class="divider-w m-t-10 m-b-20">


        <%= form_for [@league, @due] do |f| %>
          <%= f.label :amount, 'Set Buy-In: ' %>
          <%= f.text_field :amount %><br><br>

          <%= f.submit 'Submit', class: "btn btn-border-d btn-circle btn-lg"  %>

        <% end %>
        <br>

      </div>
    </div>
  </section>
<div>
        <!-- /NEW LEAGUE FORM -->



        		<!-- FOOTER -->


        		<!-- /FOOTER -->

app/views/dues/pay.js.erb
$("#main-panel").html("")
$("#main-panel").append("<%= j render :partial => 'dues/pot', locals: {league: @league}%>").hide().fadeIn()
$("#side-panel").html("")
$("#side-panel").append("<%= j render :partial => 'leagues/manage_finances', locals: {league: @league} %>").hide().fadeIn()

app/views/dues/show.html.erb
<table id='calendar'>
 <tr>
   <th>Sunday</th><th>Monday</th>
   <th>Tuesday</th><th>Wednesday</th>
   <th>Thursday</th><th>Friday</th>
   <th>Saturday</th>
  </tr>
  <tr>
  <% @beginning_of_month = Date.civil(2009, 12, 1) %>
  <% @end_of_month = Date.civil(2009, 12, -1) %>

  <% (@beginning_of_month..@end_of_month).each do |d| %>
    <% if d == @beginning_of_month %>
      <% d.wday.times do %> <td class='offset'></td> <% end %>
    <% end %>

    <% if d.wday == 0 %> </tr><tr> <% end %>
    <td> <%= d.day %> </td>
  <% end %>
  </tr>
</table>

app/views/dues/text_non_payers.js.erb
$("#side-panel").html("")
$("#side-panel").append("<div class=well well-sm'><strong>Text Sent</div>")

app/views/dues/write_text.js.erb
$("#side-panel").html("")
$("#side-panel").append("<%= j render :partial => 'dues/text' %>").hide().fadeIn()